sampl:
  messag: application-
custo:
  datasourc:
    url: jdbc:oracle:thin:@//10.21.77.108:1521/PRMSITDB
    driverClassNames: oracle.jdbc.OracleDriver
    data: "classpath*:data.sql"  
    username: RULEENGINE
    password: ENC(iMUc05+jvuD5U1AjgDu2EQ==)

