custom:
  datasource:
    url: jdbc:oracle:thin:@//10.21.77.108:1521/PRMSITDB
    driverClassNames: oracle.jdbc.OracleDriver
    data: "classpath*:data.sql"  
    username: si_ims
    password: Aghtjh#gh7
